// This file is automatically generated. Do not edit it directly.
import { createMockClient } from './mock';

// FORCED LOCAL MODE - DISCONNECTED FROM SUPABASE
// O usuário solicitou explicitamente isolamento total e uso local.
export const supabase = createMockClient() as any;

